#!/bin/bash

if [ "$1" == 'autoconf' ]; then
  echo 'yes'
  exit
fi

CARRIER=${0##*tough-rate-csr_}

if [ "$1" == 'config' ]; then
  cat <<EOT
graph_title CSR for $CARRIER
graph_vlabel CSR
graph_category voice
csr.label Call Success Rate
csr.type ABSOLUTE
csr.min 0
csr.colour ffcc00
csr.cdef success,attempts,1,attempts,0,EQ,IF,/,100,*,UNKN,attempts,0,EQ,IF,UNKN,attempts,UNKN,EQ,IF

attempts.label not_used
attempts.type DERIVE
attempts.min 0
success.label not_used
success.type DERIVE
success.min 0
EOT
  exit 0
fi

curl -s 'http://127.0.0.1:5704/statistics' \
  | jq -r "
\"attempts.value \(.[\"call-attempts\"].count)
success.value \(.["connected-calls"].count)\""
